# SQLite Configuration
#quarkus.datasource.db-kind=other
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.driver=org.sqlite.JDBC
quarkus.datasource.jdbc.url=jdbc:sqlite:database.db

# Hibernate ORM Configuration
quarkus.hibernate-orm.dialect=org.hibernate.community.dialect.SQLiteDialect
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.packages=caixa.pedro.entity
